// packages/proposal-studio/examples/angular/proposal-studio.component.ts
// Angular usage for <proposal-studio>. Works on Angular 7 through 22+.
//
//   npm install proposal-studio
//
// The ONE required step on every Angular version: allow unknown elements by
// adding CUSTOM_ELEMENTS_SCHEMA, and `import 'proposal-studio'` once to
// register the custom element.
//
// ── Angular 15+ (standalone component) ──────────────────────────────────────
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  Input,
  Output,
  EventEmitter
} from '@angular/core';
import 'proposal-studio'; // registers <proposal-studio>
import type { ProposalStudioElement } from 'proposal-studio';

@Component({
  selector: 'app-proposal-studio',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <proposal-studio
      #ed
      (ready)="onReady()"
      (change)="onChange($event)"
      style="display:block;min-height:600px"
    ></proposal-studio>
  `
})
export class ProposalStudioComponent implements AfterViewInit {
  @ViewChild('ed') edRef!: ElementRef<ProposalStudioElement>;

  @Input() value = '';
  @Output() valueChange = new EventEmitter<string>();
  @Output() ready = new EventEmitter<ProposalStudioElement>();

  private get el() {
    return this.edRef.nativeElement;
  }

  ngAfterViewInit() {
    if (this.value) this.el.whenReady().then(() => this.el.setHtml(this.value));
  }

  onReady() {
    this.ready.emit(this.el);
  }

  // Native CustomEvent — read the payload off $event.detail.
  onChange(event: Event) {
    this.valueChange.emit((event as CustomEvent<{ html: string }>).detail.html);
  }

  /** Read the current document on demand (e.g. on a Save click). */
  getHtml(): string {
    return this.el.getHtml();
  }
}

// ── Angular 7–14 (NgModule based) ───────────────────────────────────────────
// Same idea, just register the schema on your @NgModule instead of the
// component, and drop `standalone: true`:
//
//   import 'proposal-studio';
//   @NgModule({
//     declarations: [AppComponent],
//     schemas: [CUSTOM_ELEMENTS_SCHEMA],
//   })
//   export class AppModule {}
//
// In the template use the element exactly the same way:
//   <proposal-studio (ready)="..." (change)="..."></proposal-studio>

// packages/proposal-studio/examples/react/ProposalStudio.jsx
// React wrapper for <proposal-studio>.
//
//   npm install proposal-studio
//
// React 19+ passes unknown props/events to custom elements natively. For React
// 18 and below, bind imperatively via a ref (shown here) — works on every
// React version.
import { useEffect, useRef } from 'react';
import 'proposal-studio'; // registers the <proposal-studio> element

export default function ProposalStudio({ value, onChange, onReady, style }) {
  const ref = useRef(null);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;

    const handleChange = (e) => onChange && onChange(e.detail.html);
    const handleReady = () => onReady && onReady(el);

    el.addEventListener('change', handleChange);
    el.addEventListener('ready', handleReady);
    return () => {
      el.removeEventListener('change', handleChange);
      el.removeEventListener('ready', handleReady);
    };
  }, [onChange, onReady]);

  // Push controlled value into the element once it is ready.
  useEffect(() => {
    const el = ref.current;
    if (el && value != null) el.whenReady().then(() => el.setHtml(value));
  }, [value]);

  return <proposal-studio ref={ref} style={style} />;
}

// Usage:
//
//   import ProposalStudio from './ProposalStudio';
//
//   function App() {
//     const [html, setHtml] = useState('<h1>Edit me</h1>');
//     return (
//       <ProposalStudio
//         value={html}
//         onChange={setHtml}
//         onReady={() => console.log('ready')}
//         style={{ display: 'block', minHeight: 600 }}
//       />
//     );
//   }
